apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: madabank-ingress
  namespace: madabank
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - api.madabank.art
      secretName: madabank-tls
  rules:
    - host: api.madabank.art
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: madabank-api
                port:
                  number: 80
