apiVersion: v1
kind: Service
metadata:
  name: madabank-api
  namespace: madabank
spec:
  selector:
    app: madabank-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
